name: Publish to NPM
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: login to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          git config --global user.name "rubybb"
          npm whoami

      - name: install dependencies
        run: npm i

      - name: build package
        run: tsc

      - name: checkout documentation branch
        uses: actions/checkout@v2
        with:
          repository: rubybb/modrinth.js.org
          path: docs

      - name: build documentation
        run: npx typedoc

      - name: commit documentation
        run: |
          git clone https://rubybb:${{ secrets.GH_ACCESS_TOKEN }}@github.com/rubybb/modrinth.js.org.git docs
          cd docs
          git add *
          git commit -m "update documentation (?)" -a
          git push

      - name: release package
        run: |
          cd lib
          cp ../readme.md .
          npm publish